first attempt to make a self-reporting build script (and cronjob) for imagebuilder

diff --git a/profile/templates/application/builder/build_script.erb b/profile/templates/application/builder/build_script.erb
--- a/profile/templates/application/builder/build_script.erb
+++ b/profile/templates/application/builder/build_script.erb
@@ -1,10 +1,13 @@
 #!/bin/bash
-set -euxo pipefail
+set -x
 
 . <%= @rc_file %>
 
-# FIXME: Debug user
-touch /tmp/$(date +"%Y-%m-%d_%H%M")
+# Each build script will write a machine-readable report of the last build
+# in JSONL format. There will also be a dated log file in plain text containing
+# the raw output of imagebuilder.
+plain_log=/var/log/imagebuilder/<%= @name -%>-build-$(date +"%Y%m%d").log
+json_report=/var/log/imagebuilder/<%= @name %>-report.jsonl
 
 # Hack to find packer in /usr/bin/ when run as root
 export PATH=/usr/bin:/usr/local/bin:/bin:/usr/local/sbin:/usr/sbin
@@ -29,7 +32,26 @@ export PATH=/usr/bin:/usr/local/bin:/bin:/usr/local/sbin:/usr/sbin
 -d \
 -x \
 -v \
---debug
+--debug &> $plain_log
+
+imagebuilder_ec=$?
+
+# We set the shell's error handling options here to avoid exiting before a
+# report has been written
+set -euo pipefail
+
+# Write imagebuilder's exit code to imagebuilder report
+jq -Rn '{"result_imagebuilder": input}' <<< $imagebuilder_ec > $json_report
+
+# Convert newlines in imagebuilder's output into to literal \n for a
+# single-line value in the report
+awk '{printf "%s\\n", $0}' $plain_log \
+| jq -R '{"output_imagebuilder": .}' >> $json_report
+
+# Non-zero exit codes from imagebuilder must be handled manually
+if [ $imagebuilder_ec -ne 0 ]; then
+  exit 1
+fi
 
 # Compress image
 filename=/opt/images/public_builds/<%= @name %>-$(date +"%Y%m%d").qcow2
@@ -48,3 +70,6 @@ fi
 
 # Remove old images, always keeping the two most recent
 find /opt/images/public_builds/ -type f -iname <%= @name %>\* | sort -r | tail -n +3 | xargs rm -f
+
+# If we make it to here we assume the build has been successful
+jq -n '{"result": "success"}' >> $json_report
